/* ============================================================================
 *  STARTER RUN (generated by tools/bake-starter.js: do not edit by hand)
 *  The run a first visit opens with: one dropper, C E G C down four bars, a pail. Solved with the song solver
 *  and CANON; its beat grid starts on the first note, so each bar sits on a beat dot.
 * ========================================================================== */
const STARTER_LAYOUT = {"v":1,"name":"My marble run","tempo":100,"board":{"w":1000,"h":3000},"pieces":[{"id":"p1","type":"dropper","x":501.244,"y":100,"rot":0,"schedule":{"mode":"manual"}},{"id":"p2","type":"bar","x":497.3617,"y":224.6972,"rot":15,"len":84,"note":"C4"},{"id":"p3","type":"rail","x":584.1374,"y":335.399,"rot":-21,"len":70,"note":"E4"},{"id":"p4","type":"bar","x":484.3937,"y":414.5373,"rot":35,"len":78,"note":"G4"},{"id":"p5","type":"bar","x":612.3381,"y":551.9207,"rot":-65,"len":72,"note":"C5"},{"id":"p6","type":"bucket","x":551.3451,"y":627.8087,"rot":0,"w":70}],"timing":{"start":0.383333,"beatsPerBar":4}};
